User belongs to experiment group 'pythonaacf'
User belongs to experiment group 'pythonJediLSP'
User belongs to experiment group 'pythonDiscoveryModuleWithoutWatcher'
User belongs to experiment group 'pythonTensorboardExperiment'
User belongs to experiment group 'pythonSurveyNotificationcf'
User belongs to experiment group 'PythonPyTorchProfiler'
User belongs to experiment group 'pythonDeprecatePythonPath'
User belongs to experiment group 'pythonSortEnvs'
> D:\Users\dusvl\anaconda3\envs\hw\python.exe -c "import sys;print(sys.executable)"
> D:\Users\dusvl\anaconda3\envs\hw\python.exe -c "import sys;print(sys.executable)"
> D:\Users\dusvl\anaconda3\envs\hw\python.exe -c "import sys;print(sys.executable)"
> D:\Users\dusvl\anaconda3\envs\hw\python.exe -c "import sys;print(sys.executable)"
> D:\Users\dusvl\anaconda3\envs\hw\python.exe -c "import sys;print(sys.executable)"
> D:\Users\dusvl\anaconda3\envs\hw\python.exe -c "import sys;print(sys.executable)"
> D:\Users\dusvl\anaconda3\envs\hw\python.exe -c "import sys;print(sys.executable)"
> D:\Users\dusvl\anaconda3\envs\hw\python.exe -c "import sys;print(sys.executable)"
Starting Pylance language server.
Error 2021-08-26 14:12:45: Failed to check if file needs to be fixed [EntryNotFound (FileSystemError): 파일 'vscode-remote://ssh-remote+49.50.160.224/opt/ml/.config/Code/User/settings.json'(Error: 존재하지 않는 파일 'vscode-remote://ssh-remote+49.50.160.224/opt/ml/.config/Code/User/settings.json'을(를) 확인할 수 없습니다.)을(를) 읽을 수 없음
	at _handleError (/opt/ml/.vscode-server/bin/3866c3553be8b268c8a7f8c0482c0c0177aa8bfa/out/vs/server/remoteExtensionHostProcess.js:85:158459)
	at async y.readText (/opt/ml/.vscode-server/extensions/ms-python.python-2021.8.1159798656/out/client/extension.js:9:320331)
	at async p.doesFileNeedToBeFixed (/opt/ml/.vscode-server/extensions/ms-python.python-2021.8.1159798656/out/client/extension.js:59:586718)
	at async /opt/ml/.vscode-server/extensions/ms-python.python-2021.8.1159798656/out/client/extension.js:59:585845
	at async Promise.all (index 0)
	at async p.getFilesToBeFixed (/opt/ml/.vscode-server/extensions/ms-python.python-2021.8.1159798656/out/client/extension.js:59:585791)
	at async p.updateTestSettings (/opt/ml/.vscode-server/extensions/ms-python.python-2021.8.1159798656/out/client/extension.js:59:585418)] {
  code: 'FileNotFound'
}
> D:\Users\dusvl\anaconda3\envs\hw\python.exe -c "import sys;print(sys.executable)"
> D:\Users\dusvl\anaconda3\envs\hw\python.exe -c "import sys;print(sys.executable)"
Error 2021-08-26 14:12:46: Diagnostic Code: InvalidPythonInterpreterDiagnostic, Message: No Python interpreter is selected. You need to select a Python interpreter to enable features such as IntelliSense, linting, and debugging.
Diagnostic Code: InvalidPythonInterpreterDiagnostic, Message: No Python interpreter is selected. You need to select a Python interpreter to enable features such as IntelliSense, linting, and debugging.
> D:\Users\dusvl\anaconda3\envs\hw\python.exe -c "import sys;print(sys.executable)"
> D:\Users\dusvl\anaconda3\envs\hw\python.exe -c "import sys;print(sys.executable)"
Error 2021-08-26 14:13:09: Invalid Python Path 'D:\Users\dusvl\anaconda3\envs\hw\python.exe'
Python interpreter path: /opt/conda/bin/python
Error 2021-08-26 18:47:28: Error while running worker[Worker 2]. undefined
Error 2021-08-26 18:47:28: Error while running worker[Worker 1]. undefined
